language: node_js
node_js:
- '5'
env:
- CXX=g++-4.8
services:
- mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: 8c7aa75970296a3b8d3183c8a344f0e4aa067e42f0874c294eee3b35ef2bda36
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: M9DIXUAw0pULZFAtmVjvdRd3ePpn8TJIpIZCyLxNS2CQZ4KhUDPUXet3kAgJZ9qsDMt8cPqF4GxugqDxOQpwBF7aAE7Pz7MPEockOn4Pv3GaRFPfjoq6m43FFS2kqddfBaW16fMhVSfoCVc/sKuNetfRrSbOG0mfplkws8giXJqiZSgSl2TgTF/x2Iw3+ohzOfueqIbqPtkSa2hvBDSd3Qflod8w94TTUkho6ug9FPy47t3xBOk2nR1+v5f5JhyhAuF5HzwLDAWq9vaZKuao148IXNMZvFP/ow/xJxjK9f1A06LHD1lhqTsFQdbKR/1fba6wUekb/qBo9dNkI1At4M9qhRQKUSS/n6NT8oF+A3v2RobsXDuLbq+2/tUr7xWLex77wUPZTBrBHmRrNnKyW4Ii9deHXnBi7HOKW5TgUsUBaW/UyZwIeOmzVk8ClQ1ktEe0JaT7jdgCRPL1hjvr+hBb/3RnCsV+OddVCX0funuJkLtodc1se3JNozVvDKQRXO+1h5TvuQPdkra2z/e3w+tlxVQ5zI8PKTx+dZwS6rk05QTJTDHgf1KyD5Hyh7u0TIIIFUxbwu1qSRVg1C2Xw+EWU62JDvOm/GbPosDCGVL0urdWcJGJ6cU3rvj2EMttG7uLjR37kzcwXqOGIFFkXID3bhJNf4tnBmod4BRBs80=
  on:
    tags: true
    branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
